# -*- coding: utf-8 -*-
"""Generating CSV from data for jobs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lhN_ZO7SFgECKqXGwBjMlU9fj_QWyCIt
"""

import requests
from bs4 import BeautifulSoup
import csv
page = requests.get("https://realpython.github.io/fake-jobs/")
soup = BeautifulSoup(page.content, 'html.parser')

all_jobs_list = []

all_jobs = soup.select('div.is-half')

for job in all_jobs:
 job_title = job.find('h2').text.strip()
 company = job.select('h3.subtitle')[0].text.strip()
 location = job.select('p.location')[0].text.strip()
 date = job.select('time')[0].text.strip()

all_jobs_list.append({
    "job": job_title,
    "company": company,
    "location": location,
    "date": date,
})
for job in all_jobs_list:
  print(job)

  keys = all_jobs_list[0].keys()

  with open('jobs.csv', 'w', newline='') as output_file:
    dict_writer = csv.DictWriter(output_file, keys)
    dict_writer.writeheader()
    dict_writer.writerows(all_jobs_list)



